apiVersion: apps/v1
kind: Deployment
metadata:
  name: flogin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flogin
  template:
    metadata:
      labels:
        app: flogin
    spec:
      containers:
        - name: flogin #postgres
          image: 'novikva/flasklogin:latest'
          imagePullPolicy: Always #IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          env:
            - name: POSTGRES_DB_HOST
              value: service-postgres.default.svc.cluster.local
            - name: POSTGRES_DB_USER
              value: postgres
            - name: POSTGRES_DB_NAME
              value: 'web'
            - name: POSTGRES_DB_PASS
              value: '123'             
            - name: POSTGRES_DB_PORT
              value: 5432              
