apiVersion: v1
kind: Service
metadata:
  name: flogin
  labels:
    app: flogin
spec:
  selector:
    app: flogin
  ports:
  - name: flogin
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
