version: "3.9"
services:
  flasklogin:
    container_name: flogin
    image: novikva/flasklogin:latest
    environment:
      POSTGRES_DB_USER: ${PG_USERNAME}
      POSTGRES_DB_PASS: ${PG_PASSWORD}
      POSTGRES_DB_NAME: ${PG_DATABASE}
      POSTGRES_DB_HOST: ${PG_HOST}
      POSTGRES_DB_PORT: ${PG_PORT}

    restart: always
    networks:
      - fnet
    ports:
      - "8080:80"
    depends_on:
      - postgres
  postgres:
    container_name: pg
    image: postgres:13.3
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - fnet
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
volumes:
  postgres-data:
networks:
  fnet:
