name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy image
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa 
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: create and scp docker-compose and env
        run: |
          echo "${{ secrets.COMPOSE }}" > ~/docker-compose.yaml
          echo "${{ secrets.ENV }}" > ~/.env
          scp ~/docker-compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/${{ secrets.WORK_DIR }}
          scp ~/.env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/${{ secrets.WORK_DIR }}
          rm ~/docker-compose.yaml
          rm ~/.env
      - name: connect, pull and up
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ${{ secrets.WORK_DIR }} && cd ${{ secrets.WORK_DIR }} && mv ~/.docker-compose.yaml . && mv ~/.env . && docker compose pull && docker compose up -d && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
