name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy image
    runs-on: ubuntu-22.04
    steps:
      # Copy only the docker-compose.yml to remote server home folder
      - name: copy files to target server via scp
        uses: appleboy/scp-action@v0.1.3
        with:
          context: "{{defaultContext}}:imageLogin"
          host: ${‎{ secrets.SSH_HOST }‎}
          username: ${‎{ secrets.SSH_USER }‎}
          port: 22
          key: ${‎{ secrets.SSH_PRIVATE_KEY }‎}
          source: "./docker-compose.yml,./.env"
          target: "~/.deploy/${‎{ github.event.repository.name }‎}/"

    

