name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy image
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        run: |
          #install -m 600 -d /dev/null ~/.ssh/id_rsa 
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect, pull and up
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ${{ secrets.WORK_DIR }} && cd ${{ secrets.WORK_DIR }} && ls -lsa && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
